src/main/java/com/example/stylescanner/bounded_context/item/entity/Item.java, src/main/java/com/example/stylescanner/bounded_context/item_like/entity/Item_Like.java
=> new item item_like java

src/main/java/com/example/stylescanner/feed_like/entity/Feed_Like.java, src/main/java/com/example/stylescanner/item/entity/Item.java, src/main/java/com/example/stylescanner/item_like/entity/Item_Like.java
=> feed_like, item, item_like entity 생성 #3

src/main/java/com/example/stylescanner/StylescannerApplication.java, src/main/java/com/example/stylescanner/comment/entity/Comment.java, src/main/java/com/example/stylescanner/feed_like/entity/Feed_Like.java, src/main/java/com/example/stylescanner/follow/entity/Follow.java, src/main/java/com/example/stylescanner/item/entity/Item.java, src/main/java/com/example/stylescanner/item_like/entity/Item_Like.java, src/main/java/com/example/stylescanner/post/entity/Post.java, src/main/java/com/example/stylescanner/user/entity/User.java
- Post, Follow, Comment 엔티티 추가
- 엔티티 수정, @builder 어노테이션 추가
https://shout-to-my-mae.tistory.com/305 < 여기 정리 잘 되어 있어요
- closes #4 로 Issue 닫기 실험
=> 엔티티 생성 및 수정 closes #4

build.gradle, src/main/java/com/example/stylescanner/StylescannerApplication.java, src/main/java/com/example/stylescanner/item/api/ItemApi.java, src/main/java/com/example/stylescanner/item/controller/ItemController.java, src/main/java/com/example/stylescanner/item/repository/ItemRepository.java, src/main/java/com/example/stylescanner/item/service/ItemService.java, src/main/java/com/example/stylescanner/swagger/config/SwaggerConfig.java
Swagger라고, 간단하게 어떤 api가 있고 어떻게 쓰는지 문서화 해주는건데 나중에 천천히 보시면 될 것 같아요
http://localhost:9000/swagger-ui/index.html
pull 하고 실행해서 위에 주소로 접속하면 볼 수 있구요
간단하게 db에 Item 테스트 데이터 넣어 두고 틀만 짜 뒀어요
Api <- Controller <- Service <- Repository <- Entity 간단하게 보면 이런식으로 연결 되는데 나중에 Dto같은거 쓰면 조금 더 복잡해질 수도 있어요
- Repository
JpaRepository만 상속하면 findAll(), findAllById() 같은 기본적인 메소드 사용 가능
복잡한 쿼리 필요할 땐 여기서 쿼리문 작성 가능
- Service
Service는 Repository 의존
지금은 목록조회하는 list 함수랑 특정 id 아이템 조회하는 read만 구현해뒀어요
- Controller
Controller는 Service 의존
Api 인터페이스 상속
- Api
Tag, Operation 어노테이션은 swagger 어노테이션
/api/item 주소로 get 요청이 오면 list, /api/item/1로 get 요청 오면 read 메서드 호출 이런 식이에요
구현하실 땐 역순으로 Api부터 구현하는게 편할 수도 있어요
일단 시험공부부터 하시고 끝나면 이런식으로 구현하면 될 것 같슴다
=> Swagger 초기 설정 closes #8

src/main/java/filter/CorsFilter.java
=> CorsFilter 구현

src/main/java/com/example/stylescanner/instagram/api/InstagramApi.java, src/main/java/com/example/stylescanner/instagram/controller/InstagramController.java, src/main/java/com/example/stylescanner/instagram/dto/CelebInstaResponseDto.java, src/main/java/com/example/stylescanner/instagram/dto/CelebProfileResponseDto.java, src/main/java/com/example/stylescanner/instagram/dto/FeedDto.java, src/main/java/com/example/stylescanner/instagram/dto/HomeFeedResponseDto.java, src/main/java/com/example/stylescanner/instagram/service/InstagramService.java, src/main/java/com/example/stylescanner/instagram/util/InstagramGraphApiUtil.java
close #22 #20
- 추가 : Instagram Api, Controller, Service, 관련 dto 
- 수정 : InstagramGraphApiUtil
=> feat: Instagram api 구현 - 셀럽 계정 상세 조회, 홈 피드 

src/main/java/com/example/stylescanner/config/SwaggerConfig.java, src/main/java/com/example/stylescanner/config/WebMvcConfig.java
=> cors 관련 WebMvcConfig 구현

src/main/java/com/example/stylescanner/config/WebMvcConfig.java, src/main/java/com/example/stylescanner/security/config/SecurityConfig.java
SecurityConfig에 corsConfigurationSource 관련 코드 추가했습니다.
=> cors 관련 코드 추가

src/main/java/com/example/stylescanner/follow/api/FollowApi.java, src/main/java/com/example/stylescanner/follow/controller/FollowController.java, src/main/java/com/example/stylescanner/follow/repository/FollowRepository.java, src/main/java/com/example/stylescanner/follow/service/FollowService.java, src/main/java/com/example/stylescanner/instagram/util/InstagramGraphApiUtil.java
프론트에서 API 추가 요청이 있어서 추가했슴다 
셀럽 아이디를 params로 넘겨주면 현재 사용자가 해당 셀럽의 팔로잉을 체크하여 반환합니다. 
팔로잉 되어 있으면 false 안되어있으면 true 반환
=> Follow API 기능 추가 - checkFollowing

src/main/java/com/example/stylescanner/user/api/UserApi.java, src/main/java/com/example/stylescanner/user/controller/UserController.java, src/main/java/com/example/stylescanner/user/dto/UserRegisterResponseDto.java, src/main/java/com/example/stylescanner/user/service/UserService.java
User -> dto 
birthdate(localdate) -> birthdate(string) 으로 수정했슴다
=> User 마이페이지 반환 형태 수정

src/main/java/com/example/stylescanner/instagram/service/InstagramService.java, src/main/java/com/example/stylescanner/instagram/util/InstagramGraphApiUtil.java
홈 피드에 올라오는 피드는 하위 미디어(CAROUSEL_ALBUM) 에도 오로지 IMAGE 타입만 불러오도록 했슴다 
이전에는 젤 첫 미디어만 IMAGE인지 체크해서 
하위 미디어에 비디오도 섞여서 올라가서 수정했슴다 
closes #32
=> readHomeFeed 수정

src/main/java/com/example/stylescanner/comment/api/CommentApi.java, src/main/java/com/example/stylescanner/comment/controller/CommentController.java, src/main/java/com/example/stylescanner/comment/dto/CommentCreateDto.java, src/main/java/com/example/stylescanner/comment/dto/CommentDto.java, src/main/java/com/example/stylescanner/comment/entity/Comment.java, src/main/java/com/example/stylescanner/comment/repository/CommentRepository.java, src/main/java/com/example/stylescanner/comment/service/CommentService.java, src/main/java/com/example/stylescanner/error/GlobalExceptionHandler.java, src/main/java/com/example/stylescanner/error/StateResponse.java, src/main/java/com/example/stylescanner/post/api/PostApi.java, src/main/java/com/example/stylescanner/post/controller/PostController.java, src/main/java/com/example/stylescanner/post/dto/PostCreateDto.java, src/main/java/com/example/stylescanner/post/dto/PostDto.java, src/main/java/com/example/stylescanner/post/entity/Post.java, src/main/java/com/example/stylescanner/post/repository/PostRepository.java, src/main/java/com/example/stylescanner/post/service/PostService.java
StateResponse는 요청 성공이나 실패 알려줘야 하는 상황 생길 때 아래처럼 사용하시면 될 것 같아요
`return ResponseEntity.ok(StateResponse.builder().code("SUCCESS").message("댓글을 성공적으로 생성했습니다.").build());`
=> 커뮤니티 관련 기능 구현

build.gradle, src/main/java/com/example/stylescanner/config/S3Config.java
=> s3 의존성 및 config 파일 추가

src/main/java/com/example/stylescanner/user/api/UserApi.java, src/main/java/com/example/stylescanner/user/controller/UserController.java, src/main/java/com/example/stylescanner/user/service/UserService.java
/api/user/update -> 프로필 이미지 외 다른 정보 수정 시 사용 
/api/user/updateProfile -> 프로필 이미지 수정 시 사용 
update,withdrawal 의 반환 형식 true/false -> ResponseEntity<StateResponse>로 수정
=> 사용자 프로필 이미지 등록 api 추가 및 user api 반환 형식 수정 

src/main/java/com/example/stylescanner/instagram/util/InstagramGraphApiUtil.java, src/main/java/com/example/stylescanner/user/service/UserService.java
프로필 이미지 업로드 api에서 오류가 있어서 수정했습니다 
오류 사항: 기존 프사가 null일때 오류남 -> 이전 프사를 삭제하는 과정에서 오류발생 
홈에 끌고 오는 피드 갯수도 너무 과부하인거 같아서 셀럽당 가장 최근 게시물 하나씩 가져오는 걸로 수정했슴다
=> 프로필 이미지 오류 개선 + 홈 피드 갯수 수정

src/main/java/com/example/stylescanner/follow/api/FollowApi.java, src/main/java/com/example/stylescanner/follow/controller/FollowController.java, src/main/java/com/example/stylescanner/follow/dto/RecommendResponseDto.java, src/main/java/com/example/stylescanner/follow/repository/FollowRepository.java, src/main/java/com/example/stylescanner/follow/service/FollowService.java, src/main/java/com/example/stylescanner/instagram/api/InstagramApi.java, src/main/java/com/example/stylescanner/instagram/controller/InstagramController.java, src/main/java/com/example/stylescanner/instagram/dto/FeedDto.java, src/main/java/com/example/stylescanner/instagram/dto/FeedRequestDto.java, src/main/java/com/example/stylescanner/instagram/service/InstagramService.java, src/main/java/com/example/stylescanner/instagram/util/InstagramGraphApiUtil.java
closes #39 
최대 6명 셀럽 추천 
사용자가 현재 팔로우 하고 있는 셀럽과 함께 팔로잉 되어 있는 셀럽의 쌍의 빈도수 순으로 셀럽 계정 목록 반환(최대 6명)
=> 셀럽 추천 API 구현 

src/main/java/com/example/stylescanner/item/category/Category.java, src/main/java/com/example/stylescanner/item/dto/ItemDto.java, src/main/java/com/example/stylescanner/item/entity/Item.java, src/main/java/com/example/stylescanner/notification/api/NotificationApi.java, src/main/java/com/example/stylescanner/notification/controller/NotificationController.java, src/main/java/com/example/stylescanner/notification/repository/NotificationRepository.java, src/main/java/com/example/stylescanner/notification/service/NotificationService.java, src/main/java/com/example/stylescanner/post/controller/PostController.java
알림 읽음 처리, 알림 삭제, 읽지 않은 알림 개수 API 구현
=> 알림 API 추가 구현

src/main/java/com/example/stylescanner/instagram/util/InstagramGraphApiUtil.java
배우 천우희 최근 3개 피드 중 비디오 미디어 섬네일 이미지 반환 결과
=> modify: 셀럽 추천 시 비디오 섬네일 반환

src/main/java/com/example/stylescanner/item/dto/ItemDto.java, src/main/java/com/example/stylescanner/item/entity/Item.java
=> shoppingLink 컬럼 추가

src/main/java/com/example/stylescanner/instagram/dto/HomeFeedResponseDto.java, src/main/java/com/example/stylescanner/instagram/service/InstagramService.java, src/main/java/com/example/stylescanner/instagram/util/InstagramGraphApiUtil.java
=> feat: /home API에 하위 미디어 갯수 반환 추가

src/main/java/com/example/stylescanner/instagram/api/InstagramApi.java, src/main/java/com/example/stylescanner/instagram/controller/InstagramController.java, src/main/java/com/example/stylescanner/instagram/dto/HomeFeedResponseDto.java, src/main/java/com/example/stylescanner/instagram/service/InstagramService.java, src/main/java/com/example/stylescanner/instagram/util/InstagramGraphApiUtil.java
=> 인스타 이미지 URL 프록시 API 개발

src/main/java/com/example/stylescanner/comment/dto/CommentDto.java, src/main/java/com/example/stylescanner/item/api/ItemApi.java, src/main/java/com/example/stylescanner/item/controller/ItemController.java, src/main/java/com/example/stylescanner/item/entity/Item.java, src/main/java/com/example/stylescanner/item/repository/ItemRepository.java, src/main/java/com/example/stylescanner/item/service/ItemService.java, src/main/java/com/example/stylescanner/itemLike/repository/ItemLikeRepository.java
- 아이템 랭킹 상위 100개만 반환하도록 변경
- 댓글 작성 시간 반환
- 커뮤니티 데이터(Post, Comment, Notification) 초기화 #69
=> 아이템 랭킹 api, CommentDto 수정

src/main/java/com/example/stylescanner/StylescannerApplication.java
서버랑 rds timezone은 KST로 문제가 없는데 안되길래 아예 Spring boot 실행할 때 timezone 설정했습니다.
머지해봐야 할 것 같아서 일단 머지 해보겠습니다
=> Spring boot Timezone 설정

src/main/java/com/example/stylescanner/instagram/api/InstagramApi.java, src/main/java/com/example/stylescanner/instagram/util/InstagramGraphApiUtil.java
오류를 찾아준 은주야 고마워 너 코드 때문이 아니었단다...
=> modify : /home 및 /carouselMedia 피드 이미지 1개일때 에러 수정

src/main/java/com/example/stylescanner/item/api/ItemApi.java, src/main/java/com/example/stylescanner/item/controller/ItemController.java, src/main/java/com/example/stylescanner/item/dto/ItemCreateDto.java, src/main/java/com/example/stylescanner/item/dto/ItemDto.java, src/main/java/com/example/stylescanner/item/entity/Item.java, src/main/java/com/example/stylescanner/item/service/ItemService.java
/googleLens 반환값에 category만 추가해서 넘겨주면 됩니다.
바로 머지 해둘게요
=> 아이템 추가 api 구현
